<?php

namespace BlogBundle\Repository;

/**
 * Categoria_TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Categoria_TicketRepository extends \Doctrine\ORM\EntityRepository
{
}
