<?php

namespace BlogBundle\Repository;

/**
 * Historial_TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Historial_TicketRepository extends \Doctrine\ORM\EntityRepository
{
}
