<?php

namespace BlogBundle\Repository;

/**
 * Usuario_CategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Usuario_CategoriaRepository extends \Doctrine\ORM\EntityRepository
{
}
