<?php

namespace Proxies\__CG__\BlogBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Ticket extends \BlogBundle\Entity\Ticket implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'BlogBundle\\Entity\\Ticket' . "\0" . 'id', '' . "\0" . 'BlogBundle\\Entity\\Ticket' . "\0" . 'idTicket', '' . "\0" . 'BlogBundle\\Entity\\Ticket' . "\0" . 'fechaCreado', '' . "\0" . 'BlogBundle\\Entity\\Ticket' . "\0" . 'fechaStatus', '' . "\0" . 'BlogBundle\\Entity\\Ticket' . "\0" . 'fechaCierre', '' . "\0" . 'BlogBundle\\Entity\\Ticket' . "\0" . 'descripcionProblema', '' . "\0" . 'BlogBundle\\Entity\\Ticket' . "\0" . 'categoria', '' . "\0" . 'BlogBundle\\Entity\\Ticket' . "\0" . 'status', '' . "\0" . 'BlogBundle\\Entity\\Ticket' . "\0" . 'prioridad', '' . "\0" . 'BlogBundle\\Entity\\Ticket' . "\0" . 'usuarioSolicitanteId', '' . "\0" . 'BlogBundle\\Entity\\Ticket' . "\0" . 'usuarioAsignadoId'];
        }

        return ['__isInitialized__', '' . "\0" . 'BlogBundle\\Entity\\Ticket' . "\0" . 'id', '' . "\0" . 'BlogBundle\\Entity\\Ticket' . "\0" . 'idTicket', '' . "\0" . 'BlogBundle\\Entity\\Ticket' . "\0" . 'fechaCreado', '' . "\0" . 'BlogBundle\\Entity\\Ticket' . "\0" . 'fechaStatus', '' . "\0" . 'BlogBundle\\Entity\\Ticket' . "\0" . 'fechaCierre', '' . "\0" . 'BlogBundle\\Entity\\Ticket' . "\0" . 'descripcionProblema', '' . "\0" . 'BlogBundle\\Entity\\Ticket' . "\0" . 'categoria', '' . "\0" . 'BlogBundle\\Entity\\Ticket' . "\0" . 'status', '' . "\0" . 'BlogBundle\\Entity\\Ticket' . "\0" . 'prioridad', '' . "\0" . 'BlogBundle\\Entity\\Ticket' . "\0" . 'usuarioSolicitanteId', '' . "\0" . 'BlogBundle\\Entity\\Ticket' . "\0" . 'usuarioAsignadoId'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Ticket $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdTicket($idTicket)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdTicket', [$idTicket]);

        return parent::setIdTicket($idTicket);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdTicket()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTicket', []);

        return parent::getIdTicket();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCreado($fechaCreado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCreado', [$fechaCreado]);

        return parent::setFechaCreado($fechaCreado);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCreado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCreado', []);

        return parent::getFechaCreado();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaStatus($fechaStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaStatus', [$fechaStatus]);

        return parent::setFechaStatus($fechaStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaStatus', []);

        return parent::getFechaStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCierre($fechaCierre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCierre', [$fechaCierre]);

        return parent::setFechaCierre($fechaCierre);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCierre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCierre', []);

        return parent::getFechaCierre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcionProblema($descripcionProblema)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcionProblema', [$descripcionProblema]);

        return parent::setDescripcionProblema($descripcionProblema);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcionProblema()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcionProblema', []);

        return parent::getDescripcionProblema();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoria($categoria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoria', [$categoria]);

        return parent::setCategoria($categoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoria', []);

        return parent::getCategoria();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrioridad($prioridad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrioridad', [$prioridad]);

        return parent::setPrioridad($prioridad);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrioridad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrioridad', []);

        return parent::getPrioridad();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioSolicitanteId($usuarioSolicitanteId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioSolicitanteId', [$usuarioSolicitanteId]);

        return parent::setUsuarioSolicitanteId($usuarioSolicitanteId);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioSolicitanteId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioSolicitanteId', []);

        return parent::getUsuarioSolicitanteId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioAsignadoId($usuarioAsignadoId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioAsignadoId', [$usuarioAsignadoId]);

        return parent::setUsuarioAsignadoId($usuarioAsignadoId);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioAsignadoId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioAsignadoId', []);

        return parent::getUsuarioAsignadoId();
    }

}
